SUBJECT = 1;
FS = 40;
NUM_PATTERNS = 8;

N_CLUSTERS_ARR = [15:10:45];
N_STATES_ARR = [4:2:12];
CHANGE_POINT_METHOD_ARR = [2:4];
POLYNOME_DEGREE_ARR = [1:4];

ACCEPT_LIKELYHOOD_ARR = [-25, -30, - 35];
ACCEPT_LIKELYHOOD_FEAT_ARR = [-30, -40, -50];
HMM_TOLERANCE_ARR = [0.0001];

CHANGE_POINT_MINDIST_ARR = [8];

N_CLUSTERS = 25;
N_STATES = 10;
CHANGE_POINT_METHOD = 2;
POLYNOME_DEGREE = 2;

%HMM_TOLERANCE = 0.0001;
HMM_TOLERANCE = 0.0001;
MAX_SEGMENTS = 100;
ACCEPT_LIKELYHOOD = -35;
ACCEPT_LIKELYHOOD_FEAT = -60;
CHANGE_POINT_MINDIST = POLYNOME_DEGREE * 3;

CALIBRATION_MIN = 475;
CALIBRATION_MAX = 515;
SMOOTHING_INDEX = 1;

PATTERN_NO = 8;

keySet =   {'NUM_PATTERNS', 'POLYNOME_DEGREE', 'N_CLUSTERS', 'N_STATES', 'CHANGE_POINT_METHOD', 'HMM_TOLERANCE', 'MAX_SEGMENTS', 'ACCEPT_LIKELYHOOD', 'ACCEPT_LIKELYHOOD_FEAT', 'CHANGE_POINT_MINDIST', 'CALIBRATION_MAX', 'CALIBRATION_MIN', 'SMOOTHING_INDEX', 'PATTERN_NO'};
valueSet = [NUM_PATTERNS, POLYNOME_DEGREE, N_CLUSTERS, N_STATES, CHANGE_POINT_METHOD, HMM_TOLERANCE, MAX_SEGMENTS, ACCEPT_LIKELYHOOD, ACCEPT_LIKELYHOOD_FEAT, CHANGE_POINT_MINDIST, CALIBRATION_MAX, CALIBRATION_MIN, SMOOTHING_INDEX, PATTERN_NO];
Config = containers.Map(keySet,valueSet);

addpath('Data/Prepared');